import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from "next/link";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
          <body className={inter.className}>
              <nav className="flex gap-6 bg-slate-500">
                  <Link className="bg-blue-300 p-2 rounded-md" href={"/"}>
                      Home
                  </Link>
                  <Link
                      className="bg-blue-300 p-2 rounded-md"
                      href={"/testing/arbolito777"}
                  >
                      Dynamic @testing/[any]
                  </Link>
                  <Link
                      className="bg-blue-300 p-2 rounded-md"
                      href={"/my-property-the-best"}
                  >
                      Dynamic @[details]
                  </Link>
                  <Link
                      className="bg-blue-300 p-2 rounded-md"
                      href={"/search/the-error-and-fix-it"}
                  >
                      Dynamic @search/[searchSlug]
                  </Link>
                  <Link
                      className="bg-blue-300 p-2 rounded-md"
                      href={"/timeout-bug"}
                  >
                      Testing timeout in vercel
                  </Link>
              </nav>
              {children}
          </body>
      </html>
  );
}
